theme: jekyll-theme-architect

title: "stanh.com"
description: Bookmark this to keep an eye on my updates!
name: Stan Holmes

url: "https://stanh.com"
baseurl: ""

# Optional but recommended
show_downloads: false
github_username: stan-holmes   # your actual GitHub username (lowercase)
facebook_url: "https://www.facebook.com/stanholmes"
x_url: "https://x.com/stanholmes"

permalink: /:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: default
